name: cicd

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Temp input for workflow to run adhoc'
        required: false
        default: 'Ignore this field'

  push:
    paths:
      - '**/definition_workflow*.json'
      # - '!**.md'
      # - '!**.py'
      # - '!**.js'
      # - '!.github/**'
    branches:
      - prod

jobs:
  analyzer:
    runs-on: ubuntu-latest
    steps:
      
      - name: Fetch Changed Files
        id: files
        uses: jitterbit/get-changed-files@v1
        with:
          format: 'json'

      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          # Required mail server address:
          server_address: smtp.gmail.com
          # Required mail server port:
          server_port: 465
          # Optional (recommended): mail server username:
          username: ${{secrets.MAIL_USERNAME}}
          # Optional (recommended) mail server password:
          password: ${{secrets.MAIL_PASSWORD}}
          # Required mail subject:
          subject: New Push To Master
          # Required recipients' addresses:
          to: operateorchestration@gmail.com
          # Required sender full name (address can be skipped):
          from: Operate GitHub
          # Optional whether this connection use TLS (default is true if server_port is 465)
          secure: true
          # Optional plain body:
          body: Repo->${{github.repository}} ${{ steps.files.outputs.added_modified }}
